### ISSUE TITLE
Problem in feed items after user changes his profile photo

### ISSUE THREAD

**Issue by NSElvis** [hyperoslo/mingle#11]
[@arigrandeismyqueen](http://instagram.com/arigrandeismyqueen) changed her profile photo, and now the [profile url](https://distillery.s3.amazonaws.com/profiles/profile_973839482_75sq_1395248392.jpg) is broken.

![screen shot 2014-03-31 at 10 02 27](https://cloud.githubusercontent.com/assets/1088217/2564911/f631e40a-b8aa-11e3-862d-2bf8dfbba5e8.png)

**Comment by jgorset** [comment]
I think @ohenrik indirectly fixed this in #26, actually!

**Comment by NSElvis** [comment]
![minion-gifs-15](https://cloud.githubusercontent.com/assets/1088217/6541126/e9c39e7a-c4c0-11e4-9035-28a9e2381241.gif)


:tada:
