### ISSUE TITLE
Add possibility to save different sizes of the profile images

### ISSUE THREAD

**Issue by mathiasbno** [hyperoslo/mingle#21]
If the service provides different image sizes of profile images we should save them all. Or enable configuration for witch sizes should be saved.

Twitter at least provides four sizes of images [(normal, bigger, small and original)](https://dev.twitter.com/overview/general/user-profile-images-and-banners).

I have not looked in to the other services but they should have a similar setup.

**Comment by jgorset** [comment]
I think we have two options here; downloading and resizing the images ourselves with a library like CarrierWave or Refile, or relying on alternate sizes from Twitter and Instagram (if they offer any).

**Comment by jgorset** [comment]
@ohenrik fixed this in #26!
