### ISSUE TITLE
Ruby 2.2.0 and ActiveRecord 4.1.0 bug

### ISSUE THREAD

**Issue by t0ggah** [hyperoslo/mingle#31]
Got this error on creation of a record while running the tests:
```
 NoMethodError:
       undefined method `name' for nil:NilClass
```
The internet told me that this is an issue related to the ruby version 2.2.0 and ActiveRecord 4.1.0(Fixed in 4.1.2):
[https://github.com/activescaffold/active_scaffold/issues/380](https://github.com/activescaffold/active_scaffold/issues/380)
[https://github.com/rails/rails/issues/18991](https://github.com/rails/rails/issues/18991)

**Comment by jgorset** [comment]
I love that internet guy.

**Comment by jgorset** [comment]
Can/should we fix this somehow in Mingle? If suppose we could look at the Ruby and ActiveRecord versions and warn if they're broken, but that's sort of a weird thing for a gem to do.

**Comment by timkurvers** [comment]
This fixes it locally, but I'm not sure whether the Gemspec will get evaluated by RubyGems on upload or on install:

```
if RUBY_VERSION >= '2.2'
  s.add_dependency "rails", "~> 4.1.2"
else
  s.add_dependency "rails", "~> 4.0"
end
```

**Comment by t0ggah** [comment]
```
# Ruby on Rails is a full-stack web framework optimized for programmer happiness and sustainable productivity.
gem 'rails', '4.1.0.rc1'
```
Removing these lines or bump up the version in the Gemfile will fix the development environment when you use the ruby 2.2. 
Since the bug is related to ActiveRecord and ruby versions this will occur without Mingle, so i don't think with need to set the different dependencies for Rails in the gem spec.

**Comment by timkurvers** [comment]
Good point. Yep, those lines need to be removed regardless, we don't want to specify Rails as a dependency twice.

**Comment by t0ggah** [comment]
Is this dependency added to the Gemfile for external testing?

**Comment by timkurvers** [comment]
It's documented a bit further down in the Gemfile:

```ruby
# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.
```

Not entirely sure what you mean with `external testing`?

**Comment by timkurvers** [comment]
I'm suspecting @jgorest may have added it to test against the release candidate without making it a requirement for applications that may be using Mingle: https://github.com/hyperoslo/mingle/commit/804c90c5f347b5924df8fa20473c9a835efeab20

**Comment by t0ggah** [comment]
External testing(build): Travis CI

**Comment by timkurvers** [comment]
Ah, I see, possibly. Mingle currently tests exclusively against Rails 4.1.0.rc1 both locally and externally since it's defined as a development dependency. I'm not entirely sure what we should be testing against though.

**Comment by jgorset** [comment]
That's correct, @timkurvers — it's for testing against another version of Ruby on Rails.

**Comment by jgorset** [comment]
Fixed in https://github.com/hyperoslo/mingle/commit/ff9f57cb97138d7f08e9b017821bb80e7f9d7539

**Comment by jgorset** [comment]
Actually fixed in https://github.com/hyperoslo/mingle/commit/1f72c9f19dac2faf79c018edca5b68983cb87f82. Thanks @timkurvers. :-)
